// go:build !ignoreWeaverGen

package value

// Code generated by "weaver generate". DO NOT EDIT.
import (
	"fmt"
	"github.com/ServiceWeaver/weaver/runtime/codegen"
)

// Local stub implementations.

// Client stub implementations.

// Server stub implementations.

// AutoMarshal implementations.

var _ codegen.AutoMarshal = &ConfName{}

func (x *ConfName) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("ConfName.WeaverMarshal: nil receiver"))
	}
	enc.String((string)(x.value))
}

func (x *ConfName) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("ConfName.WeaverUnmarshal: nil receiver"))
	}
	*(*string)(&x.value) = dec.String()
}

var _ codegen.AutoMarshal = &ProfileID{}

func (x *ProfileID) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("ProfileID.WeaverMarshal: nil receiver"))
	}
	enc.Int32(x.value)
}

func (x *ProfileID) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("ProfileID.WeaverUnmarshal: nil receiver"))
	}
	x.value = dec.Int32()
}

var _ codegen.AutoMarshal = &SlotID{}

func (x *SlotID) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("SlotID.WeaverMarshal: nil receiver"))
	}
	enc.Int32(x.value)
}

func (x *SlotID) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("SlotID.WeaverUnmarshal: nil receiver"))
	}
	x.value = dec.Int32()
}

var _ codegen.AutoMarshal = &StampCondition{}

func (x *StampCondition) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("StampCondition.WeaverMarshal: nil receiver"))
	}
	enc.String((string)(x.value))
}

func (x *StampCondition) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("StampCondition.WeaverUnmarshal: nil receiver"))
	}
	*(*string)(&x.value) = dec.String()
}

var _ codegen.AutoMarshal = &TalkID{}

func (x *TalkID) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("TalkID.WeaverMarshal: nil receiver"))
	}
	enc.Int32(x.value)
}

func (x *TalkID) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("TalkID.WeaverUnmarshal: nil receiver"))
	}
	x.value = dec.Int32()
}

var _ codegen.AutoMarshal = &TrackID{}

func (x *TrackID) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("TrackID.WeaverMarshal: nil receiver"))
	}
	enc.Int32(x.value)
}

func (x *TrackID) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("TrackID.WeaverUnmarshal: nil receiver"))
	}
	x.value = dec.Int32()
}

var _ codegen.AutoMarshal = &ViewingSeconds{}

func (x *ViewingSeconds) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("ViewingSeconds.WeaverMarshal: nil receiver"))
	}
	enc.Int32(x.value)
}

func (x *ViewingSeconds) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("ViewingSeconds.WeaverUnmarshal: nil receiver"))
	}
	x.value = dec.Int32()
}
