linters:
  enable:
    - bodyclose
    - errorlint
    - exhaustive
    - goconst
    - godot
    - gosec
    - gocognit
    - makezero
    - misspell
    - nakedret
    - nestif
    - noctx
    - predeclared
    - unconvert
    - whitespace
linters-settings:
  gci:
    skip-generated: true
  gocognit:
    min-complexity: 20
  nestif:
    min-complexity: 10
  exhaustive:
    default-signifies-exhaustive: true
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - goconst
        - unused
        - bodyclose
        - gosec
        - gocognit
        - nestif
