[serviceweaver]
name = "dkw-serve"
binary = "./dkw"
args = ["serve"]

[single]
listeners.graphql = {address = "0.0.0.0:8080"}

[multi]
listeners.graphql = {address = "0.0.0.0:8080"}

["dreamkast-weaver/internal/cfp/Service"]
db_user = "user"
db_password = "password"
db_endpoint = "db"
db_port = "3306"
db_name = "cfp"

["dreamkast-weaver/internal/dkui/Service"]
db_user = "user"
db_password = "password"
db_endpoint = "db"
db_port = "3306"
db_name = "dkui"
