package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.70

import (
	"context"
	"dreamkast-weaver/internal/application"
	"dreamkast-weaver/internal/domain/value"
	"dreamkast-weaver/internal/server/graph/model"
	"dreamkast-weaver/internal/server/middleware"
	"errors"
	"net"
)

// Vote is the resolver for the vote field.
func (r *mutationResolver) Vote(ctx context.Context, input model.VoteInput) (*bool, error) {
	var e, err error

	req := application.VoteRequest{}
	req.ConfName, e = value.NewConfName(value.ConferenceKind((input.ConfName.String())))
	err = errors.Join(err, e)
	req.TalkID, e = value.NewTalkID(int32(input.TalkID))
	err = errors.Join(err, e)
	req.ClientIp = net.ParseIP(middleware.ClientIPFromContext(ctx))
	if err != nil {
		return nil, err
	}

	if err := r.cfpApp.Vote(ctx, req); err != nil {
		return nil, err
	}
	return nil, nil
}

// StampOnline is the resolver for the stampOnline field.
func (r *mutationResolver) StampOnline(ctx context.Context, input model.StampOnlineInput) (*bool, error) {
	var e, err error
	profile, err := newProfile(input.ConfName, input.ProfileID)
	err = errors.Join(err, e)

	slotID, e := value.NewSlotID(int32(input.SlotID))
	err = errors.Join(err, e)
	if err != nil {
		return nil, err
	}

	if err := r.stampRallyApp.StampOnline(ctx, profile, slotID); err != nil {
		return nil, err
	}
	return nil, nil
}

// StampOnSite is the resolver for the stampOnSite field.
func (r *mutationResolver) StampOnSite(ctx context.Context, input model.StampOnSiteInput) (*bool, error) {
	var e, err error
	profile, err := newProfile(input.ConfName, input.ProfileID)
	err = errors.Join(err, e)

	req := application.StampRequest{}
	req.TrackID, e = value.NewTrackID(int32(input.TrackID))
	err = errors.Join(err, e)
	req.TalkID, e = value.NewTalkID(int32(input.TalkID))
	err = errors.Join(err, e)
	req.SlotID, e = value.NewSlotID(int32(input.SlotID))
	err = errors.Join(err, e)
	if err != nil {
		return nil, err
	}

	if err := r.stampRallyApp.StampOnSite(ctx, profile, req); err != nil {
		return nil, err
	}
	return nil, nil
}

// CreateViewEvent is the resolver for the createViewEvent field.
func (r *mutationResolver) CreateViewEvent(ctx context.Context, input model.CreateViewEventInput) (*bool, error) {
	var e, err error
	profile, err := newProfile(input.ConfName, input.ProfileID)
	err = errors.Join(err, e)

	req := application.CreateViewEventRequest{}
	req.TrackID, e = value.NewTrackID(int32(input.TrackID))
	err = errors.Join(err, e)
	req.TalkID, e = value.NewTalkID(int32(input.TalkID))
	err = errors.Join(err, e)
	req.SlotID, e = value.NewSlotID(int32(input.SlotID))
	err = errors.Join(err, e)
	if err != nil {
		return nil, err
	}

	if err := r.stampRallyApp.CreateViewEvent(ctx, profile, req); err != nil {
		return nil, err
	}
	return nil, nil
}

// ViewTrack is the resolver for the ViewTrack field.
func (r *mutationResolver) ViewTrack(ctx context.Context, input model.ViewTrackInput) (*bool, error) {
	pID, err := value.NewProfileID(int32(input.ProfileID))
	if err != nil {
		return nil, err
	}
	tn, err := value.NewTrackName(input.TrackName)
	if err != nil {
		return nil, err
	}
	tID, err := value.NewTalkID(int32(input.TalkID))
	if err != nil {
		return nil, err
	}

	if err := r.vcManager.ViewTrack(ctx, pID, tn, tID); err != nil {
		return nil, err
	}
	return nil, nil
}

// VoteCounts is the resolver for the voteCounts field.
func (r *queryResolver) VoteCounts(ctx context.Context, confName model.ConfName, votingTerm *model.VotingTerm, spanSeconds *int) ([]*model.VoteCount, error) {
	vcn, err := value.NewConfName(value.ConferenceKind((confName.String())))
	if err != nil {
		return nil, err
	}

	var vvt value.VotingTerm
	if votingTerm == nil {
		vvt, err = value.NewVotingTerm(nil, nil)
	} else {
		vvt, err = value.NewVotingTerm(votingTerm.Start, votingTerm.End)
	}
	if err != nil {
		return nil, err
	}

	vss, err := value.NewSpanSeconds(spanSeconds)
	if err != nil {
		return nil, err
	}

	req := application.VoteCountsRequest{
		ConfName:    vcn,
		VotingTerm:  vvt,
		SpanSeconds: vss,
	}

	resp, err := r.cfpApp.VoteCounts(ctx, req)
	if err != nil {
		return nil, err
	}

	var counts []*model.VoteCount
	for _, v := range resp {
		counts = append(counts, &model.VoteCount{
			TalkID: int(v.TalkID.Value()),
			Count:  v.Count,
		})
	}

	return counts, nil
}

// ViewingSlots is the resolver for the viewingSlots field.
func (r *queryResolver) ViewingSlots(ctx context.Context, confName model.ConfName, profileID int) ([]*model.ViewingSlot, error) {
	profile, err := newProfile(confName, profileID)
	if err != nil {
		return nil, err
	}

	devents, err := r.stampRallyApp.ViewingEvents(ctx, profile)
	if err != nil {
		return nil, err
	}

	var viewingSlots []*model.ViewingSlot
	for k, v := range devents.ViewingSeconds() {
		viewingSlots = append(viewingSlots, &model.ViewingSlot{
			SlotID:      int(k.Value()),
			ViewingTime: int(v),
		})
	}

	return viewingSlots, nil
}

// StampChallenges is the resolver for the stampChallenges field.
func (r *queryResolver) StampChallenges(ctx context.Context, confName model.ConfName, profileID int) ([]*model.StampChallenge, error) {
	profile, err := newProfile(confName, profileID)
	if err != nil {
		return nil, err
	}

	dstamps, err := r.stampRallyApp.StampChallenges(ctx, profile)
	if err != nil {
		return nil, err
	}

	var stamps []*model.StampChallenge
	for _, dst := range dstamps.Items {
		stamps = append(stamps, &model.StampChallenge{
			SlotID:    int(dst.SlotID.Value()),
			Condition: model.ChallengeCondition(dst.Condition.Value()),
			UpdatedAt: int(dst.UpdatedAt.Unix()),
		})
	}

	return stamps, nil
}

// ViewerCount is the resolver for the viewerCount field.
func (r *queryResolver) ViewerCount(ctx context.Context, confName *model.ConfName) ([]*model.ViewerCount, error) {
	dvcs, err := r.vcManager.ListViewerCounts(ctx)
	if err != nil {
		return nil, err
	}

	var vcs []*model.ViewerCount
	for _, dvc := range dvcs.Items {
		vcs = append(vcs, &model.ViewerCount{
			TrackName: dvc.TrackName.String(),
			Count:     int(dvc.Count),
		})
	}
	return vcs, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
