services:
  dev-app:
    build:
      context: ../
      dockerfile: dev/app/Dockerfile
    environment:
      SERVICEWEAVER_CONFIG: weaver.toml
      UID: ${UID}
      XDG_DATA_HOME: /mnt
      PROM_PUSHGATEWAY_ENDPOINT: localhost:9091
    working_dir: /app
    network_mode: host
    #ports:
    #  - "8080:8080"
    volumes:
      - ../:/app
      - ${HOME}/.local/share/serviceweaver/:/mnt/serviceweaver
  db:
    image: mysql/mysql-server:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      DREAMKAST_ADDR: https://staging.dev.cloudnativedays.jp
      TZ: 'Asia/Tokyo'
    cap_add:
      - SYS_NICE
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_0900_ai_ci --default-authentication-plugin=mysql_native_password
    volumes:
    - mysql-data:/var/lib/mysql
    - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
    - "13306:3306"
  pushgateway:
    image: prom/pushgateway:v1.6.0
    ports:
      - 9091:9091
volumes:
  mysql-data:
