// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package repo

import (
	"database/sql"
	"time"
)

type CfpVote struct {
	ConferenceName string
	TalkID         int32
	CreatedAt      time.Time
	GlobalIp       sql.NullString
}

type SchemaMigration struct {
	Version string
}
