// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: query.sql

package mysql

import (
	"context"
	"time"
)

const insertCfpVote = `-- name: InsertCfpVote :exec
INSERT INTO cfp_votes (
  conference_name,
  talk_id,
  dt
) VALUES ( 
  ?, ?, ?
)
`

type InsertCfpVoteParams struct {
	ConferenceName string
	TalkID         int32
	Dt             time.Time
}

func (q *Queries) InsertCfpVote(ctx context.Context, arg InsertCfpVoteParams) error {
	_, err := q.db.ExecContext(ctx, insertCfpVote, arg.ConferenceName, arg.TalkID, arg.Dt)
	return err
}

const listCfpVoteByConferenceName = `-- name: ListCfpVoteByConferenceName :many
SELECT conference_name, talk_id, dt FROM cfp_votes
WHERE conference_name = ?
`

func (q *Queries) ListCfpVoteByConferenceName(ctx context.Context, conferenceName string) ([]CfpVote, error) {
	rows, err := q.db.QueryContext(ctx, listCfpVoteByConferenceName, conferenceName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CfpVote
	for rows.Next() {
		var i CfpVote
		if err := rows.Scan(&i.ConferenceName, &i.TalkID, &i.Dt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCfpVotes = `-- name: ListCfpVotes :many
SELECT conference_name, talk_id, dt FROM cfp_votes
`

func (q *Queries) ListCfpVotes(ctx context.Context) ([]CfpVote, error) {
	rows, err := q.db.QueryContext(ctx, listCfpVotes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CfpVote
	for rows.Next() {
		var i CfpVote
		if err := rows.Scan(&i.ConferenceName, &i.TalkID, &i.Dt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
