package gateway

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.28

import (
	"context"
	"dreamkast-weaver/service/gateway/model"
	"fmt"
)

// VoteCfp is the resolver for the voteCfp field.
func (r *mutationResolver) VoteCfp(ctx context.Context, input model.VoteCfpInput) (*model.VoteCfpPayload, error) {
	panic(fmt.Errorf("not implemented: VoteCfp - voteCfp"))
}

// VotingPapers is the resolver for the votingPapers field.
func (r *queryResolver) VotingPapers(ctx context.Context) ([]*model.VotingPaper, error) {
	panic(fmt.Errorf("not implemented: VotingPapers - votingPapers"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
