// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewVote struct {
	ConfName string `json:"confName"`
	TalkID   string `json:"talkId"`
	GlobalIP string `json:"globalIp"`
}

type VoteCount struct {
	TalkID string `json:"talkId"`
	Count  int    `json:"count"`
}
