// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewVote struct {
	ConfName string `json:"confName"`
	TalkID   int    `json:"talkId"`
	GlobalIP string `json:"globalIp"`
}

type VoteCount struct {
	TalkID int `json:"talkId"`
	Count  int `json:"count"`
}
