// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: query.sql

package repo

import (
	"context"
	"encoding/json"
)

const getTrailmapStamps = `-- name: GetTrailmapStamps :one
SELECT
  conference_name, profile_id, stamps
FROM
  trailmap_stamps
WHERE
  conference_name = ?
  AND profile_id = ?
`

type GetTrailmapStampsParams struct {
	ConferenceName string
	ProfileID      int32
}

func (q *Queries) GetTrailmapStamps(ctx context.Context, arg GetTrailmapStampsParams) (TrailmapStamp, error) {
	row := q.db.QueryRowContext(ctx, getTrailmapStamps, arg.ConferenceName, arg.ProfileID)
	var i TrailmapStamp
	err := row.Scan(&i.ConferenceName, &i.ProfileID, &i.Stamps)
	return i, err
}

const insertWatchEvents = `-- name: InsertWatchEvents :exec
INSERT INTO
  watch_events (profile_id, conference_name, track_id, talk_id, slot_id, viewing_seconds, created_at)
VALUES
  (?, ?, ?, ?, ?, ?, NOW())
`

type InsertWatchEventsParams struct {
	ProfileID      int32
	ConferenceName string
	TrackID        int32
	TalkID         int32
	SlotID         int32
	ViewingSeconds int32
}

func (q *Queries) InsertWatchEvents(ctx context.Context, arg InsertWatchEventsParams) error {
	_, err := q.db.ExecContext(ctx, insertWatchEvents,
		arg.ProfileID,
		arg.ConferenceName,
		arg.TrackID,
		arg.TalkID,
		arg.SlotID,
		arg.ViewingSeconds,
	)
	return err
}

const listWatchEvents = `-- name: ListWatchEvents :many
SELECT
  conference_name, profile_id, track_id, talk_id, slot_id, viewing_seconds, created_at
FROM
  watch_events
WHERE
  conference_name = ?
  AND profile_id = ?
`

type ListWatchEventsParams struct {
	ConferenceName string
	ProfileID      int32
}

func (q *Queries) ListWatchEvents(ctx context.Context, arg ListWatchEventsParams) ([]WatchEvent, error) {
	rows, err := q.db.QueryContext(ctx, listWatchEvents, arg.ConferenceName, arg.ProfileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WatchEvent
	for rows.Next() {
		var i WatchEvent
		if err := rows.Scan(
			&i.ConferenceName,
			&i.ProfileID,
			&i.TrackID,
			&i.TalkID,
			&i.SlotID,
			&i.ViewingSeconds,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTrailmapStamp = `-- name: UpsertTrailmapStamp :exec
REPLACE
  trailmap_stamps (conference_name, profile_id, stamps)
VALUES
  (?, ?, ?)
`

type UpsertTrailmapStampParams struct {
	ConferenceName string
	ProfileID      int32
	Stamps         json.RawMessage
}

func (q *Queries) UpsertTrailmapStamp(ctx context.Context, arg UpsertTrailmapStampParams) error {
	_, err := q.db.ExecContext(ctx, upsertTrailmapStamp, arg.ConferenceName, arg.ProfileID, arg.Stamps)
	return err
}
