// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type VoteCfpInput struct {
	ConferenceName string `json:"conferenceName"`
	TalkID         int    `json:"talkId"`
}

type VoteCfpPayload struct {
	VotingPaper *VotingPaper `json:"votingPaper"`
}

type VotingPaper struct {
	ConferenceName string `json:"conferenceName"`
	TalkID         int    `json:"talkId"`
}
